c330ae: Add back remove packages
* Still not enough partition size even moved to dynpart

RuntimeError: sum of sizes of ['odm', 'product', 'system', 'system_ext', 'vendor'] is greater than BOARD_SUPER_PARTITION_SIZE: 44216320+3567071232+1299656704+648871936+616677376 == 6176493568 > 4831838208 == 4831838208